---
- hosts: all
  become: True
  vars:
    home: '/home/vagrant'
  vars_files:
    - ../defaults/main.yml

  tasks:
    - name: Add NeoVim yum repo
      yum_repository:
        name: neovim
        description: NeoVim repo
        file: external_repos
        baseurl: 'https://copr-be.cloud.fedoraproject.org/results/dperson/neovim/epel-7-$basearch/'

    - name: Install epel-release package
      yum:
        name: epel-release
        state: latest

    - name: Install packages
      yum:
        name: '{{ item }}'
        state: latest
        disable_gpg_check: yes
      with_items: '{{ hostvars[inventory_hostname]["packages"] }}'
      register: packages

    - debug:
        var: packages

    - name: Set shell to ZSH
      shell: chsh -s /bin/zsh vagrant

    - include: ../tasks/tmux.yml
    - include: ../tasks/terraform.yml

    # - name: Install Python packages
    #   pip:
    #     requirements: '../requirements.txt'
        # name: '{{ item.name }}'
        # version: '{{ item.version }}'
      # with_items: ' {{ hostvars[inventory_hostname]["python_packages"] }}'

    - include: ../tasks/dotfiles.yml
    - include: ../tasks/fzf.yml
    - include: ../tasks/plugins.yml
